-- MySQL Script generated by MySQL Workbench
-- Fri Apr 25 15:24:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema webalk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webalk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webalk` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `webalk` ;

-- -----------------------------------------------------
-- Table `webalk`.`emojicategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`emojicategories` (
  `categoryId` INT NOT NULL,
  `name` VARCHAR(30) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  PRIMARY KEY (`categoryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`emojies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`emojies` (
  `emojiId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  `image` VARCHAR(255) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  `categoryID` INT NOT NULL,
  PRIMARY KEY (`emojiId`),
  INDEX `FK_emojies_emojicategories` (`categoryID` ASC) VISIBLE,
  CONSTRAINT `FK_emojies_emojicategories`
    FOREIGN KEY (`categoryID`)
    REFERENCES `webalk`.`emojicategories` (`categoryId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`emojicatconnects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`emojicatconnects` (
  `emojiId` INT NOT NULL,
  `categoryId` INT NOT NULL,
  INDEX `FK_emojicatconnects_emojies` (`emojiId` ASC) VISIBLE,
  INDEX `FK_emojicatconnects_emojicategories` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `FK_emojicatconnects_emojicategories`
    FOREIGN KEY (`categoryId`)
    REFERENCES `webalk`.`emojicategories` (`categoryId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_emojicatconnects_emojies`
    FOREIGN KEY (`emojiId`)
    REFERENCES `webalk`.`emojies` (`emojiId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`hobbies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`hobbies` (
  `hobbyId` INT NOT NULL,
  `name` VARCHAR(30) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  PRIMARY KEY (`hobbyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`images` (
  `imageId` INT NOT NULL,
  `imageName` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`imageId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`matchlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`matchlist` (
  `matchlistId` INT NOT NULL,
  `matchDate` DATE NOT NULL,
  PRIMARY KEY (`matchlistId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  `email` VARCHAR(70) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  `city` VARCHAR(80) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  `phoneNumb` VARCHAR(12) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  `gender` VARCHAR(15) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  `imageId` VARCHAR(255) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  `passw` VARCHAR(255) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  `description` VARCHAR(255) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  `hobbyId` INT NOT NULL,
  `likedId` INT NOT NULL,
  `matchListId` INT NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `FK_users_hobbies` (`hobbyId` ASC) VISIBLE,
  INDEX `FK_users_likesdislikes` (`likedId` ASC) VISIBLE,
  INDEX `FK_users_matchlist` (`matchListId` ASC) VISIBLE,
  CONSTRAINT `FK_users_hobbies`
    FOREIGN KEY (`hobbyId`)
    REFERENCES `webalk`.`hobbies` (`hobbyId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_users_likesdislikes`
    FOREIGN KEY (`likedId`)
    REFERENCES `webalk`.`likesdislikes` (`likedId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_users_matchlist`
    FOREIGN KEY (`matchListId`)
    REFERENCES `webalk`.`matchlist` (`matchlistId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`likesdislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`likesdislikes` (
  `likedId` INT NOT NULL AUTO_INCREMENT,
  `user1Id` INT NOT NULL,
  `liked` TINYINT(1) NOT NULL,
  `user2Id` INT NOT NULL,
  PRIMARY KEY (`likedId`),
  INDEX `FK_likesdislikes_users` (`user1Id` ASC) VISIBLE,
  INDEX `FK_likesdislikes_users_2` (`user2Id` ASC) VISIBLE,
  CONSTRAINT `FK_likesdislikes_users`
    FOREIGN KEY (`user1Id`)
    REFERENCES `webalk`.`users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_likesdislikes_users_2`
    FOREIGN KEY (`user2Id`)
    REFERENCES `webalk`.`users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`reports` (
  `reportId` INT NOT NULL AUTO_INCREMENT,
  `reporterId` INT NOT NULL,
  `reportedUserId` INT NOT NULL,
  `date` DATE NOT NULL,
  `description` VARCHAR(255) COLLATE 'utf8mb3_hungarian_ci' NOT NULL,
  PRIMARY KEY (`reportId`),
  INDEX `FK_reports_users` (`reporterId` ASC) VISIBLE,
  INDEX `FK_reports_users_2` (`reportedUserId` ASC) VISIBLE,
  CONSTRAINT `FK_reports_users`
    FOREIGN KEY (`reporterId`)
    REFERENCES `webalk`.`users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_reports_users_2`
    FOREIGN KEY (`reportedUserId`)
    REFERENCES `webalk`.`users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`userhobbyconnects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`userhobbyconnects` (
  `userID` INT NOT NULL,
  `hobbyId` INT NOT NULL,
  INDEX `FK_userhobbyconnects_users` (`userID` ASC) VISIBLE,
  INDEX `FK_userhobbyconnects_hobbies` (`hobbyId` ASC) VISIBLE,
  CONSTRAINT `FK_userhobbyconnects_hobbies`
    FOREIGN KEY (`hobbyId`)
    REFERENCES `webalk`.`hobbies` (`hobbyId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_userhobbyconnects_users`
    FOREIGN KEY (`userID`)
    REFERENCES `webalk`.`users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`userimageconnects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`userimageconnects` (
  `userId` INT NOT NULL,
  `imageId` INT NOT NULL,
  INDEX `FK_userimageconnects_users` (`userId` ASC) VISIBLE,
  INDEX `FK_userimageconnects_images` (`imageId` ASC) VISIBLE,
  CONSTRAINT `FK_userimageconnects_images`
    FOREIGN KEY (`imageId`)
    REFERENCES `webalk`.`images` (`imageId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_userimageconnects_users`
    FOREIGN KEY (`userId`)
    REFERENCES `webalk`.`users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`userlikedconnects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`userlikedconnects` (
  `userId` INT NOT NULL,
  `likedId` INT NOT NULL,
  INDEX `FK_userlikedconnects_users` (`userId` ASC) VISIBLE,
  INDEX `FK_userlikedconnects_likesdislikes` (`likedId` ASC) VISIBLE,
  CONSTRAINT `FK_userlikedconnects_likesdislikes`
    FOREIGN KEY (`likedId`)
    REFERENCES `webalk`.`likesdislikes` (`likedId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_userlikedconnects_users`
    FOREIGN KEY (`userId`)
    REFERENCES `webalk`.`users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`usermatches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`usermatches` (
  `userId` INT NOT NULL,
  `matchlistId` INT NOT NULL,
  INDEX `FK_usermatches_users` (`userId` ASC) VISIBLE,
  INDEX `FK_usermatches_matchlist` (`matchlistId` ASC) VISIBLE,
  CONSTRAINT `FK_usermatches_matchlist`
    FOREIGN KEY (`matchlistId`)
    REFERENCES `webalk`.`matchlist` (`matchlistId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_usermatches_users`
    FOREIGN KEY (`userId`)
    REFERENCES `webalk`.`users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webalk`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webalk`.`messages` (
  `messageid` INT NOT NULL,
  `user1id` INT NULL,
  `user2id` INT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`messageid`),
  UNIQUE INDEX `messageid_UNIQUE` (`messageid` ASC) VISIBLE,
  INDEX ` user1id_idx` (`user1id` ASC) VISIBLE,
  INDEX `user2id_idx` (`user2id` ASC) VISIBLE,
  CONSTRAINT ` user1id`
    FOREIGN KEY (`user1id`)
    REFERENCES `webalk`.`users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user2id`
    FOREIGN KEY (`user2id`)
    REFERENCES `webalk`.`users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
